import type { CardDef, TreasureDef } from '../../game/types'

// ---------------------------------------------------------------------------
// Token cards generated by Trapper signature treasure effects.
// Any token referenced in a signature card MUST also exist in hunterCards.
// These are the same ids as in data/cards/hunter.ts; we reference them here
// only for the embedded CardDef inside each TreasureDef.card.
// ---------------------------------------------------------------------------

/**
 * The Whole Quiver — 5-mana Trapper spell.
 * Deal 5 damage to a target and 2 damage to all other enemies.
 * (Every bolt the widow owns, loosed at once.)
 */
const killCommandBarrageCard: CardDef = {
  id: 'sig_hunter_kill_command_barrage',
  name: 'The Whole Quiver',
  cost: 5,
  type: 'spell',
  cardClass: 'hunter',
  rarity: 'legendary',
  text: 'Deal 5 damage to an enemy and 2 damage to all other enemies.',
  flavor: 'Aim is a luxury. Volume is a virtue.',
  targeted: true,
  targetFilter: 'allEnemyCharacters',
  spell: [
    { kind: 'damage', amount: 5, target: 'chosenTarget' },
    { kind: 'damage', amount: 2, target: 'otherEnemies' },
  ],
  token: true,
}

/**
 * Mangle-Jaw Snare — 5-mana Trapper spell.
 * Destroy a minion. Draw a card.
 * (Approximated as destroy + draw; the engine has no Attack-based destroy filter,
 * so this is an unconditional targeted destroy. Costed at 5 — a clean destroy
 * plus a cantrip; the original 2 mana was ~3-4 mana under-costed for that effect.)
 */
const ratTrapCard: CardDef = {
  id: 'sig_hunter_rat_trap',
  name: 'Mangle-Jaw Snare',
  cost: 5,
  type: 'spell',
  cardClass: 'hunter',
  rarity: 'legendary',
  text: 'Destroy a minion. Draw a card.',
  flavor: "Sized for bear, bailiff, or bishop. The moor doesn't discriminate.",
  targeted: true,
  targetFilter: 'allMinions',
  spell: [
    { kind: 'destroy', target: 'chosenTarget' },
    { kind: 'draw', count: 1 },
  ],
  token: true,
}

/**
 * The Widow Herself — 7-mana 4/4 legendary minion.
 * Omen: deal 2 damage to all enemy minions and summon three 1/1 Hounds with
 * Charge. (The engine cannot count dying minions, so the Hound count is a fixed 3;
 * re-costed from 5-mana 4/6 — board AoE plus a full hound-pack on a big
 * body was ~3 mana over even for a pushed signature.)
 */
const widowHerselfCard: CardDef = {
  id: 'sig_hunter_tavish_stormpike',
  name: 'The Widow Herself',
  cost: 7,
  type: 'minion',
  cardClass: 'hunter',
  rarity: 'legendary',
  text: '**Omen:** Deal 2 damage to all enemy minions. Summon three 1/1 Hounds with **Charge**.',
  flavor: "She doesn't knock. Neither do the hounds.",
  attack: 4,
  health: 4,
  tribe: 'none',
  battlecry: [
    { kind: 'damage', amount: 2, target: 'enemyMinions' },
    { kind: 'summon', token: 'hunter_hound', count: 3 },
  ],
  token: true,
}

/**
 * Powder-Keg Bolt — 4-mana Trapper spell.
 * Deal 5 damage to a minion and 2 damage to adjacent ones — an
 * adjacency splash (adjacentToTarget), distinct from The Whole Quiver's
 * face-reaching all-enemy spray and costed BELOW it (its targeting is narrower).
 */
const explosiveShotCard: CardDef = {
  id: 'sig_hunter_explosive_shot',
  name: 'Powder-Keg Bolt',
  cost: 4,
  type: 'spell',
  cardClass: 'hunter',
  rarity: 'legendary',
  text: 'Deal 5 damage to a minion and 2 damage to adjacent ones.',
  flavor: 'Lit, loosed, and lamented. In that order.',
  targeted: true,
  targetFilter: 'allMinions',
  spell: [
    { kind: 'damage', amount: 5, target: 'chosenTarget' },
    { kind: 'damage', amount: 2, target: 'adjacentToTarget' },
  ],
  token: true,
}

/**
 * Carrion Wake — 5-mana Trapper spell.
 * Summon three 1/2 Gorecrows with "Haunt: Draw a card." — the Haunt-archetype
 * signature: a sticky board that replaces itself when it dies.
 */
const carrionWakeCard: CardDef = {
  id: 'sig_hunter_carrion_wake',
  name: 'Carrion Wake',
  cost: 5,
  type: 'spell',
  cardClass: 'hunter',
  rarity: 'legendary',
  text: 'Summon three 1/2 Gorecrows with "**Haunt:** Draw a card."',
  flavor: 'A proper Hollowmoor funeral: black feathers, light fingers, open bar.',
  spell: [{ kind: 'summon', token: 'carrion_bird', count: 3 }],
  token: true,
}

/**
 * All Trapper signature treasures for Widow Bracken.
 *
 * 5 active signatures (each embeds a powerful token card).
 * 1 passive signature (Poacher's Discount aura — your Beasts cost 1 less).
 */
export const hunterSignatureTreasures: TreasureDef[] = [
  {
    id: 'sig_hunter_kill_command_barrage',
    name: 'The Whole Quiver',
    kind: 'signature',
    text: 'Deal 5 damage to an enemy and 2 damage to all other enemies.',
    card: killCommandBarrageCard,
    tags: ['hunter-good', 'damage'],
  },
  {
    id: 'sig_hunter_rat_trap',
    name: 'Mangle-Jaw Snare',
    kind: 'signature',
    text: 'Destroy a minion. Draw a card.',
    card: ratTrapCard,
    tags: ['hunter-good', 'removal'],
  },
  {
    id: 'sig_hunter_tavish_stormpike',
    name: 'The Widow Herself',
    kind: 'signature',
    text: '4/4. Omen: Deal 2 damage to all enemy minions. Summon three 1/1 Hounds with Charge.',
    card: widowHerselfCard,
    tags: ['hunter-good', 'beast'],
  },
  {
    id: 'sig_hunter_explosive_shot',
    name: 'Powder-Keg Bolt',
    kind: 'signature',
    text: 'Deal 5 damage to a minion and 2 damage to adjacent ones.',
    card: explosiveShotCard,
    tags: ['hunter-good', 'damage'],
  },
  {
    id: 'sig_hunter_carrion_wake',
    name: 'Carrion Wake',
    kind: 'signature',
    text: 'Summon three 1/2 Gorecrows with "Haunt: Draw a card."',
    card: carrionWakeCard,
    tags: ['hunter-good', 'deathrattle'],
  },
  /**
   * Poacher's Discount — PASSIVE signature.
   * Your Beasts cost (1) less. Encourages flooding the board with cheap beasts.
   */
  {
    id: 'sig_hunter_beast_bond',
    name: "Poacher's Discount",
    kind: 'signature',
    text: 'Your Beasts cost (1) less.',
    auras: [{ kind: 'costReduction', amount: 1, filter: 'beast' }],
    tags: ['hunter-good', 'beast', 'passive'],
  },
]
