import type { CardDef, TreasureDef } from '../../game/types'

// ---------------------------------------------------------------------------
// Token cards generated by Hunter signature treasure effects.
// Any token referenced in a signature card MUST also exist in hunterCards.
// These are the same ids as in data/cards/hunter.ts; we reference them here
// only for the embedded CardDef inside each TreasureDef.card.
// ---------------------------------------------------------------------------

/**
 * Kill Command Barrage — 5-mana Hunter spell.
 * Deal 5 damage to a target and 2 damage to all other enemies.
 * (A beefed-up barrage echoing Kill Command's on-theme fantasy.)
 */
const killCommandBarrageCard: CardDef = {
  id: 'sig_hunter_kill_command_barrage',
  name: 'Kill Command Barrage',
  cost: 5,
  type: 'spell',
  cardClass: 'hunter',
  rarity: 'legendary',
  text: 'Deal 5 damage to an enemy and 2 damage to all other enemies.',
  targeted: true,
  targetFilter: 'allEnemyCharacters',
  spell: [
    { kind: 'damage', amount: 5, target: 'chosenTarget' },
    { kind: 'damage', amount: 2, target: 'otherEnemies' },
  ],
  token: true,
}

/**
 * Rat Trap — 5-mana Hunter spell.
 * Destroy a minion. Draw a card.
 * (Approximated as destroy + draw; the engine has no Attack-based destroy filter,
 * so this is an unconditional targeted destroy. Costed at 5 — Assassinate plus a
 * cantrip; the original 2 mana was ~3-4 mana under-costed for that effect.)
 */
const ratTrapCard: CardDef = {
  id: 'sig_hunter_rat_trap',
  name: 'Rat Trap',
  cost: 5,
  type: 'spell',
  cardClass: 'hunter',
  rarity: 'legendary',
  text: 'Destroy a minion. Draw a card.',
  targeted: true,
  targetFilter: 'allMinions',
  spell: [
    { kind: 'destroy', target: 'chosenTarget' },
    { kind: 'draw', count: 1 },
  ],
  token: true,
}

/**
 * Tavish, Master Marksman — 7-mana 4/4 legendary minion.
 * Battlecry: deal 2 damage to all enemy minions and summon three 1/1 Hounds with
 * Charge. (The engine cannot count dying minions, so the Hound count is a fixed 3;
 * re-costed from 5-mana 4/6 — board AoE plus a full Unleash the Hounds on a big
 * body was ~3 mana over even for a pushed signature.)
 */
const tavishStormpike: CardDef = {
  id: 'sig_hunter_tavish_stormpike',
  name: 'Tavish, Master Marksman',
  cost: 7,
  type: 'minion',
  cardClass: 'hunter',
  rarity: 'legendary',
  text: '**Battlecry:** Deal 2 damage to all enemy minions. Summon three 1/1 Hounds with **Charge**.',
  attack: 4,
  health: 4,
  tribe: 'none',
  battlecry: [
    { kind: 'damage', amount: 2, target: 'enemyMinions' },
    { kind: 'summon', token: 'hunter_hound', count: 3 },
  ],
  token: true,
}

/**
 * Explosive Shot — 4-mana Hunter spell.
 * Deal 5 damage to a minion and 2 damage to adjacent ones — the real card's
 * adjacency splash (adjacentToTarget), distinct from Kill Command Barrage's
 * face-reaching all-enemy spray and costed BELOW it (its targeting is narrower).
 */
const explosiveShotCard: CardDef = {
  id: 'sig_hunter_explosive_shot',
  name: 'Explosive Shot',
  cost: 4,
  type: 'spell',
  cardClass: 'hunter',
  rarity: 'legendary',
  text: 'Deal 5 damage to a minion and 2 damage to adjacent ones.',
  targeted: true,
  targetFilter: 'allMinions',
  spell: [
    { kind: 'damage', amount: 5, target: 'chosenTarget' },
    { kind: 'damage', amount: 2, target: 'adjacentToTarget' },
  ],
  token: true,
}

/**
 * All Hunter signature treasures for Beaststalker Tavish.
 *
 * 4 active signatures (each embeds a powerful token card).
 * 1 passive signature (Beast Bond aura — your Beasts cost 1 less).
 */
export const hunterSignatureTreasures: TreasureDef[] = [
  {
    id: 'sig_hunter_kill_command_barrage',
    name: 'Kill Command Barrage',
    kind: 'signature',
    text: 'Deal 5 damage to an enemy and 2 damage to all other enemies.',
    card: killCommandBarrageCard,
    tags: ['hunter-good', 'damage'],
  },
  {
    id: 'sig_hunter_rat_trap',
    name: 'Rat Trap',
    kind: 'signature',
    text: 'Destroy a minion. Draw a card.',
    card: ratTrapCard,
    tags: ['hunter-good', 'removal'],
  },
  {
    id: 'sig_hunter_tavish_stormpike',
    name: 'Tavish, Master Marksman',
    kind: 'signature',
    text: '4/4. Battlecry: Deal 2 damage to all enemy minions. Summon three 1/1 Hounds with Charge.',
    card: tavishStormpike,
    tags: ['hunter-good', 'beast'],
  },
  {
    id: 'sig_hunter_explosive_shot',
    name: 'Explosive Shot',
    kind: 'signature',
    text: 'Deal 5 damage to a minion and 2 damage to adjacent ones.',
    card: explosiveShotCard,
    tags: ['hunter-good', 'damage'],
  },
  /**
   * Beast Bond — PASSIVE signature.
   * Your Beasts cost (1) less. Encourages flooding the board with cheap beasts.
   */
  {
    id: 'sig_hunter_beast_bond',
    name: 'Beast Bond',
    kind: 'signature',
    text: 'Your Beasts cost (1) less.',
    auras: [{ kind: 'costReduction', amount: 1, filter: 'beast' }],
    tags: ['hunter-good', 'beast', 'passive'],
  },
]
