import type { CardDef, TreasureDef } from '../../game/types';

// ---------------------------------------------------------------------------
// Moon token cards generated by The Gloaming Hound's end-of-turn trigger.
// Both are authored directly at cost (0) — The Gloaming Hound adds them via
// plain addCardToHand, so the "cost (0)" lives on the tokens themselves.
// Dark o' the Moon: deal 3 damage to a minion, draw a card.
// Full o' the Moon: originally "your next spell this turn casts twice", which
//   has no atomic engine representation; approximated as Spell Damage +2 this
//   turn.
// ---------------------------------------------------------------------------

/**
 * Dark o' the Moon token — cost 0 because The Gloaming Hound's trigger adds
 * them at cost (0).
 * Effect: deal 3 damage to a minion and draw a card.
 */
const lunarEclipseToken: CardDef = {
  id: 'lunar_eclipse_token',
  name: "Dark o' the Moon",
  cost: 0,
  type: 'spell',
  cardClass: 'druid',
  rarity: 'common',
  text: 'Deal 3 damage to a minion. Draw a card.',
  flavor: 'What\'s done under the dark of the moon stays under it. Mostly.',
  targeted: true,
  targetFilter: 'allMinions',
  spell: [
    { kind: 'damage', amount: 3, target: 'chosenTarget' },
    { kind: 'draw', count: 1 },
  ],
  token: true,
};

/**
 * Full o' the Moon token — cost 0 because The Gloaming Hound's trigger adds
 * them at cost (0).
 * Effect: give your hero Spell Damage +2 this turn (a faithful, simple stand-in
 * for the original "next spell casts twice", which has no atomic engine
 * representation).
 */
const solarEclipseToken: CardDef = {
  id: 'solar_eclipse_token',
  name: "Full o' the Moon",
  cost: 0,
  type: 'spell',
  cardClass: 'druid',
  rarity: 'common',
  text: 'Give your hero Spell Damage +2 this turn.',
  flavor: 'Come the full moon, every hedge in Hollowmoor has a couple in it and a witch above, taking notes.',
  spell: [{ kind: 'spellDamageThisTurnHero', amount: 2 }],
  token: true,
};

/**
 * The Gallows Oak — 4/12 Taunt. Battlecry: give your hero +5 Armor.
 * (Was 8/12: an 8-drop budget is ~17 stats, and 8/12 + Taunt + 5 Armor sat
 * several mana above curve even for a signature; 4/12 keeps it a pushed wall.)
 */
const awakenedAncientCard: CardDef = {
  id: 'sig_awakened_ancient',
  name: 'The Gallows Oak',
  cost: 8,
  type: 'minion',
  cardClass: 'druid',
  rarity: 'legendary',
  text: '**Omen:** Gain 5 Armor. **Ward.**',
  flavor: 'It bore every rope the county ever tied. One evening it shrugged them all off, and the hill has wanted a hangman since.',
  attack: 4,
  health: 12,
  tribe: 'ancient',
  keywords: ['taunt'],
  battlecry: [{ kind: 'gainArmor', amount: 5 }],
  scriptId: 'awakenedAncientUpgrade',
  token: true,
};

/** Morwenna the Twice-Told — 3/6. After you cast a spell that costs (4) or more, cast it again. */
const zukaraCard: CardDef = {
  id: 'sig_zukara',
  name: 'Morwenna the Twice-Told',
  cost: 6,
  type: 'minion',
  cardClass: 'druid',
  rarity: 'legendary',
  text: 'After you cast a spell that costs (4) or more, cast it again targeting random targets.',
  flavor: 'Repeats every curse she hears, and every rumour. The rumours do more damage.',
  attack: 3,
  health: 6,
  tribe: 'none',
  triggers: [
    {
      event: 'onSpellCast4Plus',
      scriptId: 'zukaraRecast',
      condition: 'cardCost4Plus',
    },
  ],
  token: true,
};

/**
 * The Gloaming Hound — 4-mana 3/5 Beast.
 * At the end of your turn, add both Moon spells to your hand. They cost (0).
 * (The discount is baked into the cost-0 tokens rather than an aura, so the
 * text says "They cost (0)" instead of "Your Moon spells cost (0)".)
 * (canonical final version: Patch 26.0.4)
 */
const moonbeastCard: CardDef = {
  id: 'sig_moonbeast',
  name: 'The Gloaming Hound',
  cost: 4,
  type: 'minion',
  cardClass: 'druid',
  rarity: 'legendary',
  text: 'At the end of your turn, add both Moon spells to your hand. They cost (0).',
  flavor: 'It howled at the moon for nine nights running, and on the tenth the moon came down to see about it.',
  attack: 3,
  health: 5,
  tribe: 'beast',
  triggers: [
    {
      event: 'endOfTurn',
      effects: [
        { kind: 'addCardToHand', cardId: 'lunar_eclipse_token', count: 1 },
        { kind: 'addCardToHand', cardId: 'solar_eclipse_token', count: 1 },
      ],
    },
  ],
  token: true,
};

/**
 * The Tupping Horn — 0/3 weapon.
 * After you play a Beast, summon a copy of it.
 * (herdingHornCopy script handles the copy + durability loss)
 */
const herdingHornCard: CardDef = {
  id: 'sig_herding_horn',
  name: 'The Tupping Horn',
  cost: 3,
  type: 'weapon',
  cardClass: 'druid',
  rarity: 'legendary',
  text: 'After you play a Beast, summon a copy of it.',
  flavor: 'One blast and every beast in the county comes running. Two, and they start pairing off — beasts, farmhands, the lot.',
  attack: 0,
  durability: 3,
  triggers: [
    {
      event: 'onPlayBeast',
      scriptId: 'herdingHornCopy',
      condition: 'cardIsBeast',
    },
  ],
  token: true,
};

/**
 * The Farmer's Almanack — 4-mana Farmer spell, Choose One.
 * Option 1: Refresh your Mana Crystals.
 * Option 2: Summon a Treant for each Mana Crystal you have.
 */
const wardensInsightCard: CardDef = {
  id: 'sig_wardens_insight',
  name: "The Farmer's Almanack",
  cost: 4,
  type: 'spell',
  cardClass: 'druid',
  rarity: 'legendary',
  text: 'Choose One - Refresh your Mana Stones; or Summon a Treant for each Mana Stone you have.',
  flavor: 'Planting times, moon signs, and which farmhands are worth the bother. Heavily annotated.',
  chooseOne: [
    {
      text: 'Refresh your Mana Stones.',
      effects: [{ kind: 'refreshMana' }],
    },
    {
      text: 'Summon a Treant for each Mana Stone.',
      effects: [{ kind: 'summonPerManaCrystal', token: 'treant' }],
    },
  ],
  token: true,
};

/**
 * Witch's Butter — 5-mana Farmer spell.
 * Shuffle 3 random Choose One cards (from your class) into your deck.
 * (Approximation: the original "3× Discover... combine its effects" — the
 * marvelousMycelium script picks the 3 cards at random with no interactive
 * Discover and without combining effects, so the text reflects that.)
 */
const marvelousMyceliumCard: CardDef = {
  id: 'sig_marvelous_mycelium',
  name: "Witch's Butter",
  cost: 5,
  type: 'spell',
  cardClass: 'druid',
  rarity: 'legendary',
  text: 'Shuffle 3 random Choose One cards into your deck.',
  flavor: 'Spread it on your bread and by morning the bread has opinions.',
  scriptId: 'marvelousMycelium',
  token: true,
};

/**
 * All signature treasures for Farmer Greg.
 * Each embeds a token:true CardDef that is added to the player's deck at run start.
 */
export const signatureTreasures: TreasureDef[] = [
  {
    id: 'sig_wardens_insight',
    name: "The Farmer's Almanack",
    kind: 'signature',
    text: 'Choose One - Refresh your Mana Stones; or Summon a Treant for each Mana Stone you have.',
    card: wardensInsightCard,
    tags: ['druid-good'],
  },
  {
    id: 'sig_herding_horn',
    name: 'The Tupping Horn',
    kind: 'signature',
    text: 'Weapon (0/3). After you play a Beast, summon a copy of it.',
    card: herdingHornCard,
    tags: ['druid-good'],
  },
  {
    id: 'sig_marvelous_mycelium',
    name: "Witch's Butter",
    kind: 'signature',
    text: 'Shuffle 3 random Choose One cards into your deck.',
    card: marvelousMyceliumCard,
    tags: ['druid-good'],
  },
  {
    id: 'sig_awakened_ancient',
    name: 'The Gallows Oak',
    kind: 'signature',
    text: '4/12. Ward. Omen: Gain 5 Armor.',
    card: awakenedAncientCard,
    tags: ['druid-good'],
  },
  {
    id: 'sig_zukara',
    name: 'Morwenna the Twice-Told',
    kind: 'signature',
    text: '3/6. After you cast a spell that costs (4) or more, cast it again targeting random targets.',
    card: zukaraCard,
    tags: ['druid-good'],
  },
  {
    id: 'sig_moonbeast',
    name: 'The Gloaming Hound',
    kind: 'signature',
    text: '3/5 Beast. At the end of your turn, add both Moon spells to your hand. They cost (0).',
    card: moonbeastCard,
    tags: ['druid-good'],
  },
];

/**
 * Moon token cards that The Gloaming Hound generates.
 * Export these so the integrator can register them in the card DB.
 */
export const signatureTreasureTokens: CardDef[] = [
  lunarEclipseToken,
  solarEclipseToken,
];
