import type { CardDef, TreasureDef } from '../../game/types';

// ---------------------------------------------------------------------------
// Eclipse token cards generated by Moonbeast's end-of-turn trigger.
// Both are authored directly at cost (0) — Moonbeast adds them via plain
// addCardToHand, so the "cost (0)" lives on the tokens themselves.
// Lunar Eclipse: deal 3 damage to a minion, draw a card.
// Solar Eclipse: originally "your next spell this turn casts twice", which has
//   no atomic engine representation; approximated as Spell Damage +2 this turn.
// ---------------------------------------------------------------------------

/**
 * Lunar Eclipse token — cost 0 because Moonbeast's trigger adds them at cost (0).
 * Effect: deal 3 damage to a minion and draw a card.
 */
const lunarEclipseToken: CardDef = {
  id: 'lunar_eclipse_token',
  name: 'Lunar Eclipse',
  cost: 0,
  type: 'spell',
  cardClass: 'druid',
  rarity: 'common',
  text: 'Deal 3 damage to a minion. Draw a card.',
  targeted: true,
  targetFilter: 'allMinions',
  spell: [
    { kind: 'damage', amount: 3, target: 'chosenTarget' },
    { kind: 'draw', count: 1 },
  ],
  token: true,
};

/**
 * Solar Eclipse token — cost 0 because Moonbeast's trigger adds them at cost (0).
 * Effect: give your hero Spell Damage +2 this turn (a faithful, simple stand-in for
 * the original "next spell casts twice", which has no atomic engine representation).
 */
const solarEclipseToken: CardDef = {
  id: 'solar_eclipse_token',
  name: 'Solar Eclipse',
  cost: 0,
  type: 'spell',
  cardClass: 'druid',
  rarity: 'common',
  text: 'Give your hero Spell Damage +2 this turn.',
  spell: [{ kind: 'spellDamageThisTurnHero', amount: 2 }],
  token: true,
};

/**
 * Awakened Ancient — 4/12 Taunt. Battlecry: give your hero +5 Armor.
 * (Was 8/12: an 8-drop budget is ~17 stats, and 8/12 + Taunt + 5 Armor sat
 * several mana above curve even for a signature; 4/12 keeps it a pushed wall.)
 */
const awakenedAncientCard: CardDef = {
  id: 'sig_awakened_ancient',
  name: 'Awakened Ancient',
  cost: 8,
  type: 'minion',
  cardClass: 'druid',
  rarity: 'legendary',
  text: '**Battlecry:** Gain 5 Armor. **Taunt.**',
  attack: 4,
  health: 12,
  tribe: 'ancient',
  keywords: ['taunt'],
  battlecry: [{ kind: 'gainArmor', amount: 5 }],
  scriptId: 'awakenedAncientUpgrade',
  token: true,
};

/** Zukara the Dark — 3/6. After you cast a spell that costs (4) or more, cast it again. */
const zukaraCard: CardDef = {
  id: 'sig_zukara',
  name: 'Zukara the Dark',
  cost: 6,
  type: 'minion',
  cardClass: 'druid',
  rarity: 'legendary',
  text: 'After you cast a spell that costs (4) or more, cast it again targeting random targets.',
  attack: 3,
  health: 6,
  tribe: 'none',
  triggers: [
    {
      event: 'onSpellCast4Plus',
      scriptId: 'zukaraRecast',
      condition: 'cardCost4Plus',
    },
  ],
  token: true,
};

/**
 * Moonbeast — 4-mana 3/5 Beast.
 * At the end of your turn, add both Eclipse spells to your hand. They cost (0).
 * (The discount is baked into the cost-0 tokens rather than an aura, so the
 * text says "They cost (0)" instead of "Your Eclipse spells cost (0)".)
 * (canonical final version: Patch 26.0.4)
 */
const moonbeastCard: CardDef = {
  id: 'sig_moonbeast',
  name: 'Moonbeast',
  cost: 4,
  type: 'minion',
  cardClass: 'druid',
  rarity: 'legendary',
  text: 'At the end of your turn, add both Eclipse spells to your hand. They cost (0).',
  attack: 3,
  health: 5,
  tribe: 'beast',
  triggers: [
    {
      event: 'endOfTurn',
      effects: [
        { kind: 'addCardToHand', cardId: 'lunar_eclipse_token', count: 1 },
        { kind: 'addCardToHand', cardId: 'solar_eclipse_token', count: 1 },
      ],
    },
  ],
  token: true,
};

/**
 * Herding Horn — 0/3 weapon.
 * After you play a Beast, summon a copy of it.
 * (herdingHornCopy script handles the copy + durability loss)
 */
const herdingHornCard: CardDef = {
  id: 'sig_herding_horn',
  name: 'Herding Horn',
  cost: 3,
  type: 'weapon',
  cardClass: 'druid',
  rarity: 'legendary',
  text: 'After you play a Beast, summon a copy of it.',
  attack: 0,
  durability: 3,
  triggers: [
    {
      event: 'onPlayBeast',
      scriptId: 'herdingHornCopy',
      condition: 'cardIsBeast',
    },
  ],
  token: true,
};

/**
 * Warden's Insight — 4-mana druid spell, Choose One.
 * Option 1: Refresh your Mana Crystals.
 * Option 2: Summon a Treant for each Mana Crystal you have.
 */
const wardensInsightCard: CardDef = {
  id: 'sig_wardens_insight',
  name: "Warden's Insight",
  cost: 4,
  type: 'spell',
  cardClass: 'druid',
  rarity: 'legendary',
  text: 'Choose One - Refresh your Mana Crystals; or Summon a Treant for each Mana Crystal you have.',
  chooseOne: [
    {
      text: 'Refresh your Mana Crystals.',
      effects: [{ kind: 'refreshMana' }],
    },
    {
      text: 'Summon a Treant for each Mana Crystal.',
      effects: [{ kind: 'summonPerManaCrystal', token: 'treant' }],
    },
  ],
  token: true,
};

/**
 * Marvelous Mycelium — 5-mana druid spell.
 * Shuffle 3 random Choose One cards (from your class) into your deck.
 * (Approximation: the original "3× Discover... combine its effects" — the
 * marvelousMycelium script picks the 3 cards at random with no interactive
 * Discover and without combining effects, so the text reflects that.)
 */
const marvelousMyceliumCard: CardDef = {
  id: 'sig_marvelous_mycelium',
  name: 'Marvelous Mycelium',
  cost: 5,
  type: 'spell',
  cardClass: 'druid',
  rarity: 'legendary',
  text: 'Shuffle 3 random Choose One cards into your deck.',
  scriptId: 'marvelousMycelium',
  token: true,
};

/**
 * All signature treasures for Forest Warden Omu.
 * Each embeds a token:true CardDef that is added to the player's deck at run start.
 */
export const signatureTreasures: TreasureDef[] = [
  {
    id: 'sig_wardens_insight',
    name: "Warden's Insight",
    kind: 'signature',
    text: 'Choose One - Refresh your Mana Crystals; or Summon a Treant for each Mana Crystal you have.',
    card: wardensInsightCard,
    tags: ['druid-good'],
  },
  {
    id: 'sig_herding_horn',
    name: 'Herding Horn',
    kind: 'signature',
    text: 'Weapon (0/3). After you play a Beast, summon a copy of it.',
    card: herdingHornCard,
    tags: ['druid-good'],
  },
  {
    id: 'sig_marvelous_mycelium',
    name: 'Marvelous Mycelium',
    kind: 'signature',
    text: 'Shuffle 3 random Choose One cards into your deck.',
    card: marvelousMyceliumCard,
    tags: ['druid-good'],
  },
  {
    id: 'sig_awakened_ancient',
    name: 'Awakened Ancient',
    kind: 'signature',
    text: '4/12. Taunt. Battlecry: Gain 5 Armor.',
    card: awakenedAncientCard,
    tags: ['druid-good'],
  },
  {
    id: 'sig_zukara',
    name: 'Zukara the Dark',
    kind: 'signature',
    text: '3/6. After you cast a spell that costs (4) or more, cast it again targeting random targets.',
    card: zukaraCard,
    tags: ['druid-good'],
  },
  {
    id: 'sig_moonbeast',
    name: 'Moonbeast',
    kind: 'signature',
    text: '3/5 Beast. At the end of your turn, add both Eclipse spells to your hand. They cost (0).',
    card: moonbeastCard,
    tags: ['druid-good'],
  },
];

/**
 * Eclipse token cards that Moonbeast generates.
 * Export these so the integrator can register them in the card DB.
 */
export const signatureTreasureTokens: CardDef[] = [
  lunarEclipseToken,
  solarEclipseToken,
];
